[pytest]
addopts = --ignore=src/sim_scripts/gazebo_camera_test.py --ignore=test/test_battery.py --ignore=samples/geofence_test.py --ignore=samples/img_test.py --ignore=src/modules/mavctl/tests/test_arm_disarm.py

# test_battery.py needs to be migrated to mavctl from dronekit
# geofence_test.py will be fixed in the migration to mavctl from dronekit
# img_test.py requires Raspberry Pi camera hardware and picamera2
