run:
	python qr.py img/qr_test.jpg
	python qr.py img/qr_test2.jpg
	python qr.py img/qr_test3.jpg
	python qr.py img/qr_test4.jpg
	python qr.py img/qr_test5.jpg
	python qr.py img/qr_test6.jpg
competition:
	python qr.py img/competition_test.jpg
