import math
import time

import dronekit


class Navigation:
    """
    A class to handle navigation.
    """

    vehicle: dronekit.Vehicle = None

    def __init__(self, vehicle):
        self.vehicle = vehicle

    def __message(self, msg):
        """
        Prints a message to the console.
        :param msg: The message to print.
        :return: None
        """

        print(f"SHEPARD_NAV: {msg}")

    def takeoff(self, target_alt):
        """
        Takes off to a given altitude. *known working*

        :param target_alt: The target altitude in meters.
        :return: True if successful, False otherwise.
        """

        self.__message(f"Taking off to {target_alt} m")
        self.vehicle.simple_takeoff(target_alt)

        while self.vehicle.location.global_relative_frame.alt < target_alt - 1:
            time.sleep(1)

        return True

    def set_position(self, lat, lon):
        """
        Moves the vehicle to a given position. *might be working?*

        :param lat: The latitude of the target position.
        :param lon: The longitude of the target position.
        :return: None
        """

        target_location = dronekit.LocationGlobalRelative(lat, lon, self.vehicle.location.global_relative_frame.alt)
        self.vehicle.simple_goto(target_location)

        while self.vehicle.mode.name == "GUIDED":
            remaining_distance = self.__get_distance_metres(self.vehicle.location.global_relative_frame,
                                                            target_location)
            self.__message(f"Distance to target: {remaining_distance} m")
            if remaining_distance <= 0.1:
                self.__message("Reached target")
                break
            time.sleep(2)

    def set_position_relative(self, d_north, d_east):
        """
        Moves the vehicle to a given position relative to its current position. *known working*

        :param d_north: The distance to move north in meters.
        :param d_east: The distance to move east in meters.
        :return: None
        """

        current_location = self.vehicle.location.global_relative_frame
        target_location = self.__get_location_metres(current_location, d_north, d_east)
        target_distance = self.__get_distance_metres(current_location, target_location)
        self.vehicle.simple_goto(target_location)

        while self.vehicle.mode.name == "GUIDED":
            remaining_distance = self.__get_distance_metres(self.vehicle.location.global_relative_frame,
                                                            target_location)
            self.__message(f"Distance to target: {remaining_distance} m")
            if remaining_distance <= target_distance * 0.01:
                self.__message("Reached target")
                break
            time.sleep(2)

    # TODO: Make sure the following methods work as intended. Generated by GitHub Copilot.

    def set_heading(self, heading):
        """
        Sets the heading of the vehicle.

        :param heading: The heading in degrees.
        :return: None
        """

        self.__message(f"Changing heading to {heading} degrees")
        #self.vehicle.simple_goto(self.vehicle.location.global_frame, heading)

        self.vehicle.commands.condition_yaw(heading)

    def set_heading_relative(self, heading):
        """
        Sets the heading of the vehicle relative to its current heading.

        :param heading: The heading in degrees.
        :return: None
        """

        self.__message(f"Changing heading to {heading} degrees relative to current heading")
        #self.vehicle.simple_goto(self.vehicle.location.global_relative_frame, self.vehicle.heading + heading)

        self.vehicle.commands.condition_yaw(heading, relative=True)

    def set_altitude(self, altitude):
        """
        Sets the altitude of the vehicle.

        :param altitude: The altitude in meters.
        :return: None
        """

        self.__message(f"Setting altitude to {altitude} m")
        #self.vehicle.simple_goto(self.vehicle.location.global_frame, self.vehicle.heading, altitude)
        
        while self.vehicle.location.global_relative_frame.alt < altitude - 1:
            self.vehicle.simple_takeoff(altitude)
            time.sleep(1)

    def set_altitude_relative(self, altitude):
        """
        Sets the altitude of the vehicle relative to its current altitude.

        :param altitude: The altitude in meters.
        :return: None
        """

        self.__message(f"Setting altitude to {altitude} m relative to current altitude")
        #self.vehicle.simple_goto(self.vehicle.location.global_frame, self.vehicle.heading,
                                 #self.vehicle.location.global_relative_frame.alt + altitude)

        target_altitude = self.vehicle.location.global_relative_frame.alt + altitude
        while self.vehicle.location.global_relative_frame.alt < target_altitude - 1:
            self.vehicle.simple_takeoff(target_altitude)
            time.sleep(1)

    def land(self):
        """
        Lands the vehicle. *known working*

        :return: None
        """

        self.__message("Landing")
        self.vehicle.mode = dronekit.VehicleMode("LAND")

    def return_to_launch(self):
        """
        Returns the vehicle to its launch position. *known working*

        :return: None
        """

        self.__message("Returning to launch")
        self.vehicle.mode = dronekit.VehicleMode("RTL")

    # END_TODO

    def __get_location_metres(self, original_location, d_north, d_east):
        """
        Returns a `LocationGlobalRelative` object containing the latitude/longitude `d_north` and `d_east` metres from the
        specified `original_location`. The returned `LocationGlobalRelative` has the same `alt` value as `original_location`. *known working*

        :param original_location: The reference `LocationGlobal`.
        :param d_north: The distance to the north in meters.
        :param d_east: The distance to the east in meters.
        :return: A `LocationGlobalRelative` object.
        """

        earth_radius = 6378137.0  # Radius of "spherical" earth
        # Coordinate offsets in radians
        d_lat = d_north / earth_radius
        d_lon = d_east / (earth_radius * math.cos(math.pi * original_location.lat / 180))

        # New position in decimal degrees
        new_lat = original_location.lat + (d_lat * 180 / math.pi)
        new_lon = original_location.lon + (d_lon * 180 / math.pi)
        if type(original_location) is dronekit.LocationGlobal:
            target_location = dronekit.LocationGlobal(new_lat, new_lon, original_location.alt)
        elif type(original_location) is dronekit.LocationGlobalRelative:
            target_location = dronekit.LocationGlobalRelative(new_lat, new_lon, original_location.alt)
        else:
            raise Exception("Invalid Location object passed")

        return target_location

    def __get_distance_metres(self, location_1, location_2):
        """
        Returns the ground distance in metres between two `LocationGlobal` or `LocationGlobalRelative` objects. *known working*

        This method is an approximation, and will not be accurate over large distances and close to the earth's poles.

        :param location_1: The first `LocationGlobal` or `LocationGlobalRelative` object.
        :param location_2: The second `LocationGlobal` or `LocationGlobalRelative` object.
        :return: The ground distance in metres.
        """

        d_lat = location_2.lat - location_1.lat
        d_lon = location_2.lon - location_1.lon

        return math.sqrt((d_lat * d_lat) + (d_lon * d_lon)) * 1.113195e5
